Repository Im-D/your-voice-front, pull requests merged in 2021-03, with the labels that each got.

#8 [lint/default props] 현재는 많이 사용하지 않는 default props 규칙 제거
  .eslintrc.js
Labels: 공통 작업

#9 [fix/alias] vite alias 중 @atoms가 정상 작동하지 않음 버그 해결
  vite.config.ts
Labels: 버그

#20 [fix/issue6] api 관련 파일 lint 맞추는 작업
  src/api/controllers/Question.ts
  src/api/controllers/utils.ts
Labels: 버그

#7 [component/text] 예시를 위한 Text 컴포넌트 개발
  src/atoms/Text/index.tsx
  src/atoms/Text/style.scss
  src/pages/Main.tsx
  src/styles/_variable.scss
Labels: 만들어주세요.

#21 [component/image] Image 컴포넌트 개발
  src/atoms/Image/index.test.jsx
  src/atoms/Image/index.tsx
  src/atoms/Image/style.scss
Labels: 새로운 기능

#23 [component/logo] Logo 컴포넌트 개발
  src/assets/Logo.png
  src/atoms/Logo/index.tsx
  src/atoms/Logo/style.scss
Labels: 새로운 기능

#22 [fix/alias] vite 및 jest alias에서 @atoms 누락된 부분 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  jest.config.js
  vite.config.ts
Labels: 버그

#24 [fix/jest] jest 관련 설정 추가
  jest.config.js
  jest.setup.js
  yarn.lock
Labels: 버그
